version: "3.8"

services:
    nginx:
        build:          ./requirements/nginx
        container_name: nginx
        restart:        always

        env_file:
            - .env
        ports:
            - 443:443
        volumes:
            - wp_data:/var/www/wordpress
        networks:
            - local
        depends_on:
            - wordpress

    wordpress:
        build:          ./requirements/wordpress
        container_name: wp
        restart:        always

        env_file:
            - .env
        volumes:
            - wp_data:/var/www/wordpress/
        networks:
            - local
        depends_on:
            - mariadb

    mariadb:
        build:          ./requirements/mariadb
        container_name: mariadb
        restart:        always

        env_file:
            - .env
        volumes:
            - sql_data:/var/lib/mysql
        networks:
            - local

    redis:
        build:          ./requirements/bonus/redis
        container_name: redis
        restart:        always

        ports:
           - 6379:6379
        networks:
            - local

    adminer:
        container_name: adminer
        build:          ./requirements/bonus/adminer
        restart:        always

        depends_on:
          - mariadb
        networks:
          - local
        ports:
          - 8080:8080

#    https://github.com/delfer/docker-alpine-ftp-server/issues/15
    ftp-server:
        container_name: ftp-server
        build:          ./requirements/bonus/ftp-server
        restart:        always

        ports:
            - 21:21
        depends_on:
            - wordpress
        env_file:
            - .env
        networks:
            - local
        volumes:
            - wp_data:/home/$FTP_USER/ftp

volumes:
    sql_data:
        driver:     local
        driver_opts:
            o:      bind
            type:   none
            device: /home/dwillard/data/mysql
    wp_data:
        driver:     local
        driver_opts:
            o:      bind
            type:   none
            device: /home/dwillard/data/wordpress
networks:
    local:
        driver: bridge
