version: "3.8"

services:
    nginx:
        build:          ./requirements/nginx
        container_name: nginx
        restart:        always

        env_file:
            - .env
        ports:
            - 443:443
        volumes:
            - /home/dwillard/data/wordpress/:/var/www/wordpress/
        networks:
            - local
        depends_on:
            - wordpress

    wordpress:
        build:          ./requirements/wordpress
        container_name: wp
        restart:        always

        env_file:
            - .env
        volumes:
            - /home/dwillard/data/wordpress/:/var/www/wordpress/
        networks:
            - local
        depends_on:
            - mariadb
    mariadb:
        build:          ./requirements/mariadb
        container_name: masha
        restart:        always

        env_file:
            - .env
        volumes:
            - sql_data:/var/lib/mysql
        networks:
            - local
volumes:
    sql_data:

networks:
    local:
        driver: bridge
